# Generated by Django 3.0.5 on 2020-04-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twiclone_api', '0003_auto_20200420_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username_slug',
        ),
    ]
