# Generated by Django 3.0.5 on 2020-04-21 03:27

from django.db import migrations, models
import twiclone_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('twiclone_api', '0007_auto_20200421_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=twiclone_api.models.content_file_name),
        ),
    ]
