# Generated by Django 3.0.5 on 2020-04-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiclone_api', '0008_auto_20200421_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
