# Generated by Django 3.0.5 on 2020-04-21 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twiclone_api', '0009_auto_20200421_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='avatar',
        ),
    ]
