# Generated by Django 3.0.5 on 2020-04-21 03:49

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields
import twiclone_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('twiclone_api', '0010_auto_20200421_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertweet',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertweet',
            name='like',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertweet',
            name='retweet',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=twiclone_api.models.content_file_name),
        ),
    ]
