# Generated by Django 3.0.6 on 2020-05-21 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twiclone_api', '0013_auto_20200521_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowers',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
