# Generated by Django 3.0.6 on 2020-05-21 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiclone_api', '0015_auto_20200521_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollower',
            name='follower_id',
            field=models.ManyToManyField(related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
