# Generated by Django 3.0.6 on 2020-05-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twiclone_api', '0016_auto_20200521_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollower',
        ),
    ]
