# Generated by Django 3.0.6 on 2020-05-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiclone_api', '0017_delete_userfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='twiclone_api.UserProfile'),
        ),
    ]
