# Generated by Django 3.0.6 on 2020-05-21 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twiclone_api', '0018_userprofile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertweet',
            name='like',
        ),
        migrations.RemoveField(
            model_name='usertweet',
            name='retweet',
        ),
        migrations.AddField(
            model_name='usertweet',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_by', to='twiclone_api.UserProfile'),
        ),
    ]
